m09w24/my-app/config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  resources :authors do
    resources :books
  end

  # Using namespaces /admin/articles
  # rails g controller admin/articles
  namespace :admin do
    resources :articles, :comments
  end

  # Shallow nesting
  resources :articles do
    resources :comments, only: [:index, :new, :create]
  end
  resources :comments, only: [:show, :edit, :update, :destroy]

  # Using the :shallow option
  resources :articles do
    resources :comments, shallow: true
  end
end

m09w24/my-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

m09w24/my-app/app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

m09w24/my-app/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

m09w24/my-app/app/models/recipe.rb
class Recipe < ApplicationRecord
end

m09w24/my-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

m09w24/my-app/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
    
    # To send json instead of default template
    render json: @authors
  end
end

m09w24/my-app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @author = Author.find(params[:author_id]);
    @books = @author.books
  end
end

m09w24/my-app/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :instructions)
    end
end

m09w24/my-app/app/helpers/application_helper.rb
module ApplicationHelper
end

m09w24/my-app/app/helpers/authors_helper.rb
module AuthorsHelper
end

m09w24/my-app/app/helpers/books_helper.rb
module BooksHelper
end

m09w24/my-app/app/helpers/recipes_helper.rb
module RecipesHelper
end

m09w24/my-app/app/views/authors/index.html.erb
<h1>All the Authors</h1>
<% @authors.each do |author| %>
  <ul>
    <li>
      <h2>
        <%= "#{author.first_name} #{author.last_name}" %> - <%= link_to 'Books', author_books_path(author)  %>
      </h2>
    </li>
  </ul>
<% end %>

m09w24/my-app/app/views/books/_book.html.erb
<div class="book">
  <%= book.title %>
</div>

m09w24/my-app/app/views/books/index.html.erb
<h1>Books for <%= @author.first_name + ' ' + @author.last_name %></h1>
<%= link_to 'Home', authors_path  %>
<% @books.each do |book| %>
  <!-- <%= render 'book', book: book %> -->
  <%= render @books %>
<% end %>

m09w24/my-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

m09w24/my-app/app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :instructions, style: "display: block" %>
    <%= form.text_area :instructions %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

m09w24/my-app/app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Title:</strong>
    <%= recipe.title %>
  </p>

  <p>
    <strong>Instructions:</strong>
    <%= recipe.instructions %>
  </p>

</div>

m09w24/my-app/app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

m09w24/my-app/app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Show this recipe", recipe %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path %>

m09w24/my-app/app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

m09w24/my-app/app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div>
  <%= link_to "Edit this recipe", edit_recipe_path(@recipe) %> |
  <%= link_to "Back to recipes", recipes_path %>

  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>